### model
model_name_or_path: /srv/scratch/z5526880/models/Qwen3-4B
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 32
lora_target: all

### dataset
dataset_dir: ../configs
dataset: sentiment_sft_train
template: qwen3_nothink
cutoff_len: 512
preprocessing_num_workers: 8
dataloader_num_workers: 8

### output
output_dir: ../output/qwen3-4B/lora/sft
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: wandb  # choices: [none, wandb, tensorboard, swanlab, mlflow]
run_name: qwen3_sft_sentiment

### train
per_device_train_batch_size: 64
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000
resume_from_checkpoint: null

### eval
eval_dataset: sentiment_sft_test
per_device_eval_batch_size: 64
eval_strategy: steps
eval_steps: 50
